[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_endpoints = { eth = "https://eth-sepolia.g.alchemy.com/v2/QlXFO2edkPcV7HHJcx89G", arb = "https://arb-sepolia.g.alchemy.com/v2/QlXFO2edkPcV7HHJcx89G"}

remappings = [
     '@openzeppelin=lib/openzeppelin-contracts/',
     '@ccip=lib/ccip/',
     '@chainlink-local=lib/chainlink-local'
]
